name = "JuliaExamples"
uuid = "4d7ea4bb-9a23-48f6-8ae5-7d575a462bde"
authors = ["Anoushka Bhutani <abhutani@umich.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
