[project]
name = "python-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cupy>=13.6.0",
    "line-profiler>=5.0.0",
    "memory-profiler>=0.61.0",
    "numpy>=2.2.6",
    "py-spy>=0.3.14",
]
